---
##
# Bridge Port
##

- name: Get .ids bridge ports
  community.routeros.api:
    hostname: "{{ inventory_hostname }}"
    port: "{{ mik_api_port }}"
    username: "{{ mik_username }}"
    password: "{{ mik_password }}"
    path: interface bridge port
    query: ".id comment WHERE comment == {{ container_desc }}_{{ bridge.name }}"
  loop: "{{ containers }}"
  loop_control:
    loop_var: bridge  
  register: bridgePortId
  tags: bridge

- debug:
    var: bridgeId
  when: debug == true
  tags: bridge

- name: Add veth interface to bridge
  community.routeros.api:
    hostname: "{{ inventory_hostname }}"
    port: "{{ mik_api_port }}"
    username: "{{ mik_username }}"
    password: "{{ mik_password }}"
    path: interface bridge port
    cmd: "add bridge={{ container_bridge }} interface={{ container_net }}_{{ item.name }} comment={{ container_desc }}_{{ item.name}}"
  loop: "{{ containers }}"
  loop_control:
    index_var: idx
  ignore_errors: yes
  register: result_add_net_bridge
  when: item.state == "present" and ('no results' in bridgePortId.results[idx].msg | default('') | string )
  tags: bridge

- debug:
    var: result_add_net_bridge
  when: debug == true
  tags: bridge

- name: Remove veth from bridge
  community.routeros.api:
    hostname: "{{ inventory_hostname }}"
    port: "{{ mik_api_port }}"
    username: "{{ mik_username }}"
    password: "{{ mik_password }}"
    path: interface bridge port
    remove: "{{ item.msg[0]['.id'] }}"
  loop: "{{ bridgePortId.results }}"
  register: result_remove_bridge_ports
  when: 
    - item.bridge is defined
    - item.bridge.state | default('present') == "absent"
    - item.msg | length > 0
    - item.msg[0]['.id'] is defined
  tags: bridge

- debug:
    var: result_remove_bridge_ports
  when: debug == true
  tags: bridge
