---
- name: Setup Veth
  import_tasks: tasks/00_setup_veth.yml

- name: Setup Bridge
  import_tasks: tasks/01_setup_bridge.yml

- name: Setup Enviroments
  import_tasks: tasks/02_setup_envs.yml
  
- name: Setup Firewall
  import_tasks: tasks/03_setup_fw.yml

- name: Setup Mounts
  import_tasks: tasks/04_setup_mounts.yml

- name: Setup Containers
  import_tasks: tasks/05_setup_containers.yml
