---
- name: Pre-task
  import_tasks: tasks/pre_tasks.yml

- name: Setup Veth
  import_tasks: tasks/00-setup_veth.yml

- name: Setup Bridge
  import_tasks: tasks/01-setup_bridge.yml

- name: Setup Enviroments
  import_tasks: tasks/02-setup_envs.yml
  
- name: Setup Firewall
  import_tasks: tasks/03-setup_fw.yml

- name: Setup Mounts
  import_tasks: tasks/04-setup_mounts.yml

- name: Setup Containers
  import_tasks: tasks/05-setup_containers.yml
